nelmio_api_doc:
    documentation:
        components:
            securitySchemes:
                    Bearer:
                        type: http
                        scheme: bearer
                        bearerFormat: JWT
            schemas:
                RegisterRequest:
                    type: object
                    properties:
                        email:
                            type: string
                            format: email
                            example: example@mail.com
                        password:
                            type: string
                            format: password
                            example: "12345"
                        firstName:
                            type: string
                            example: Example
                        lastName:
                            type: string
                            example: Examplez
                        artistName:
                            type: string
                            example: exampleRapper
                        phone:
                            type: integer
                            example: 666666666
                        location:
                            type: string
                            example: Example Location
                        genderId:
                            type: integer
                            example: 1
                        profilePictureUrl:
                            type: string
                            format: uri
                            example: "https://static.wikia.nocookie.net/ivansitorechulonlosdibujosmolanmogollon/images/9/9d/Mesichiquito.jpg/revision/latest?cb=20200922212709&path-prefix=es"
                        userGenres:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        example: 1
                        userRoles:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        example: 1
                        userLanguages:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        example: 1
                LoginRequest:
                    type: object
                    properties:
                        email:
                            type: string
                            format: email
                            example: "antonio.garcia@example.com"
                        password:
                            type: string
                            format: password
                            example: "12345"
                LoginResponse:
                    type: object
                    properties:
                        accessToken:
                            type: string
                            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                        refreshToken:
                            type: string
                            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                RefreshTokenRequest:
                    type: object
                    properties:
                        refreshToken:
                            type: string
                            example: "dGhpcyBpcyBhIHJlZnJlc2ggdG9rZW4="
                RefreshTokenResponse:
                    type: object
                    properties:
                        accessToken:
                            type: string
                            example: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                GetAllGenresResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                                example: 1
                            name:
                                type: string
                                example: "Rock"
                            description:
                                type: string
                                example: "Genre characterized by use of electric guitars, bass, and drums"
                GetAllLanguagesResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                                example: 1
                            name:
                                type: string
                                example: "English"
                            isoCode:
                                type: string
                                example: "en"
                GetPostsResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                            content:
                                type: string
                            track:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    createdAt:
                                        type: string
                                        format: date-time
                                    trackUrl:
                                        type: string
                            createdAt:
                                type: string
                                format: date-time
                            user:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    artistName:
                                        type: string
                                    firstName:
                                        type: string
                                    lastName:
                                        type: string
                                    profilePictureUrl:
                                        type: string

                CreatePostRequest:
                    type: object
                    properties:
                        content:
                            type: string
                            example: "This is my new post"
                        trackUrl:
                            type: string
                            example: "https://example.com/media.mp3"

                CreatePostResponse:
                    type: object
                    properties:
                        id:
                            type: integer
                        content:
                            type: string
                        track:
                            type: object
                            properties:
                                id:
                                    type: integer
                                createdAt:
                                    type: string
                                    format: date-time
                                trackUrl:
                                    type: string
                        createdAt:
                            type: string
                            format: date-time
                        user:
                            type: object
                            properties:
                                id:
                                    type: integer
                                artistName:
                                    type: string
                                firstName:
                                    type: string
                                lastName:
                                    type: string
                                profilePictureUrl:
                                    type: string

                GetUserPostsResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                            content:
                                type: string
                            track:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    createdAt:
                                        type: string
                                        format: date-time
                                    trackUrl:
                                        type: string
                            user:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    artistName:
                                        type: string
                                    firstName:
                                        type: string
                                    lastName:
                                        type: string
                                    profilePictureUrl:
                                        type: string
                            createdAt:
                                type: string
                                format: date-time

                GetCurrentUserResponse:
                    type: object
                    properties:
                        id:
                            type: integer
                        artistName:
                            type: string
                        firstName:
                            type: string
                        lastName:
                            type: string
                        email:
                            type: string
                        googleId:
                            type: string
                        phone:
                            type: integer
                        location:
                            type: string
                        profilePictureUrl:
                            type: string
                        createdAt:
                            type: string
                            format: date-time
                        updatedAt:
                            type: string
                            format: date-time
                        userGender:
                            type: object
                            properties:
                                id:
                                    type: integer
                                name:
                                    type: string
                        userLanguages:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    name:
                                        type: string
                                    isoCode:
                                        type: string
                        userRoles:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    name:
                                        type: string
                                    description:
                                        type: string
                        userSearchRoles:
                            type: array
                            items:
                                type: object
                        userGenres:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    name:
                                        type: string
                                    description:
                                        type: string
                        userIdentifier:
                            type: string

                EditUserRequest:
                    type: object
                    properties:
                        artistName:
                            type: string
                        firstName:
                            type: string
                        lastName:
                            type: string
                        phone:
                            type: string
                        location:
                            type: string
                        profilePictureUrl:
                            type: string
                        userGenres:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                        userRoles:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer
                        userLanguages:
                            type: array
                            items:
                                type: object
                                properties:
                                    id:
                                        type: integer

                GetUserSwiperResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            user:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                    artistName:
                                        type: string
                                    firstName:
                                        type: string
                                    lastName:
                                        type: string
                                    email:
                                        type: string
                                    profilePictureUrl:
                                        type: string
                                    gender:
                                        type: object
                                        properties:
                                            id:
                                                type: integer
                                            name:
                                                type: string
                                    userGenres:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                name:
                                                    type: string
                                                description:
                                                    type: string
                                    userLanguages:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                name:
                                                    type: string
                                                isoCode:
                                                    type: string
                                    userRoles:
                                        type: array
                                        items:
                                            type: object
                                            properties:
                                                id:
                                                    type: integer
                                                name:
                                                    type: string
                                                description:
                                                    type: string
                                    searchRoles:
                                        type: array
                                        items:
                                            type: string
                            liked:
                                type: boolean
                                nullable: true

                GetUserResponse:
                    type: object
                    properties:
                        id:
                            type: integer
                        email:
                            type: string
                        artistName:
                            type: string
                        location:
                            type: string
                GetRolesResponse:
                    type: array
                    items:
                        type: object
                        properties:
                            id:
                                type: integer
                                example: 1
                            name:
                                type: string
                                example: "Singer"
                            description:
                                type: string
                                example: "Vocal performer who uses their voice to interpret and perform musical pieces"
                SwipeUserRequest:
                    type: object
                    properties:
                        swipedUserId:
                            type: integer
                            example: 1
                        liked:
                            type: boolean
                            example: true

                SwipeUserResponse:
                    type: array
                    items:
                        type: string
                        example: "OK"